- src/main/java/com/easypost/model/Insurance.java
- src/main/java/com/easypost/model/InsuranceCollection.java
- src/test/java/com/easypost/EasyPostTest.java
Needs work for sure. Hopefully I provided a good base
> initial work for insurance top level objects

- pom.xml
- src/main/java/com/easypost/net/EasyPostResource.java
- src/test/java/com/easypost/EasyPostTest.java
Literally just copy-pasta of the POST method.
> send PUT requests via application/x-www-form-urlencoded body instead of query parameters

- src/main/java/com/easypost/model/CustomsItem.java
- src/main/java/com/easypost/model/Fee.java
- src/test/java/com/easypost/EasyPostTest.java
Adds missing properties requested in open issues for `Fee type` and `Customs Info code & currency`.
Closes #48 
Closes #51
> Adds missing properties, closes #48, closes #51

- pom.xml
> bump hamcrest dependency

- src/main/java/com/easypost/model/Shipment.java
- src/main/java/com/easypost/model/SmartrateCollection.java
- src/main/java/com/easypost/model/SmartrateCollectionDeserializer.java
- src/main/java/com/easypost/net/EasyPostResource.java
- src/test/java/com/easypost/EasyPostTest.java
- adds new SmartrateCollection object to collect a list of Rate objects
- adds new SmartrateDeserializer to handle parsing smartrate-specific response JSON schema
- utilizes RateDeserializer to parse Rate objects, store in SmartrateCollection object
- getSmartrates() function utilizes SmartrateCollection internally, returns list of Rate objects (no change in return type)
I am not sure about testing procedures yet, so this is just a draft
> fix: Smartrate deserialization

- src/main/java/com/easypost/model/EventDeserializer.java
- src/main/java/com/easypost/model/Rate.java
- src/main/java/com/easypost/model/RateDeserializer.java
- src/main/java/com/easypost/model/Shipment.java
- src/main/java/com/easypost/model/SmartrateCollection.java
- src/main/java/com/easypost/model/SmartrateCollectionDeserializer.java
- src/main/java/com/easypost/model/TimeInTransit.java
- src/main/java/com/easypost/net/EasyPostResource.java
- src/test/java/com/easypost/EasyPostTest.java
- adds TimeInTransit class
- adds TimeInTransit field to Rate
- deserializes TimeInTransit from JSON response
- adds getSmartrates function to Shipment
- adds `null` checks when deserializing JSON
- adds unit tests for `getSmartrates()`
- fix: test that was not passing by updating the expected rate
- fix: skips testWebhookCRUD test until we can fix it properly
> feat: Adds SmartRate

- .gitignore
- src/main/java/com/easypost/model/Shipment.java
- src/main/java/com/easypost/model/TaxIdentifier.java
- src/test/java/com/easypost/EasyPostTest.java
Add Tax Identifier along with the unit test.
> Adds Support for Tax Identifiers

- src/main/java/com/easypost/net/EasyPostResource.java
Pass Java version to the User-Agent in requests
> add Java version to the User-Agent in requests

- src/main/java/com/easypost/model/Shipment.java
This PR supports **one call buy** feature for our Java CL
> support one call buy

- src/main/java/com/easypost/model/CarrierType.java
This PR adds support for users to retrieve available Carrier Types.
> add support to retrieve available Carrier Types

- src/main/java/com/easypost/model/Order.java
Support one call buy order for Java library by adding service attribute in Order class and #87 add service in Shipment class.
> support one call buy order by adding service attribute in Order class.

- README.md
- Add badges to README for CI and Maven
> README badges for test status

- CHANGELOG.md
- src/main/java/com/easypost/model/Brand.java
- src/main/java/com/easypost/model/User.java
allow users to update the brand through API.
Java library is currently missing this feature.
Add Brand class and the updateBrand method in the User class.
E2E local test
> support update brand.

- src/main/java/com/easypost/model/Shipment.java
Remove duplicate code in the lowestRate() method. Current unit tests still passed.
> remove duplicate code in lowestRate() method.

- .github/workflows/ci.yml
- UPGRADE_GUIDE.md
Adds an upgrade guide to the project.
> chore: adds upgrade guide

- src/test/java/com/easypost/ShipmentTest.java
This PR adds a missing assertion for `tax_identifiers`
> add assertion for tax_identifiers.

- CHANGELOG.md
- src/main/java/com/easypost/model/Address.java
- src/test/java/com/easypost/AddressTest.java
- src/test/java/com/easypost/Fixture.java
- Removes dead `message` conditional check in Address `create and verify`
- Updates a few address assertions to match internal API changes
> removes the dead message conditional check in address create and verify.

- .github/workflows/ci.yml
- README.md
- src/test/java/com/easypost/CarrierAccountTest.java
- src/test/java/com/easypost/Fixture.java
- src/test/java/com/easypost/InsuranceTest.java
- src/test/java/com/easypost/OrderTest.java
- src/test/java/com/easypost/PickupTest.java
- src/test/java/com/easypost/ReportTest.java
- src/test/java/com/easypost/TrackerTest.java
- src/test/java/com/easypost/UserTest.java
- src/test/java/com/easypost/WebhookTest.java
The goal of this PR is to make the test suite much more bullet proof without the need to manually alter fixture data in code as well as making it easier for 3rd party contributors to test this library.
- Cleaned up various tests
- Provided more fixtures to DRY up tests
- Consolidated dates in fixtures
- Removed the hard-coded child user ID
- Added helpful instructions to the README on how to test this library (from a 3rd party contributor perspective)
> chore: more fixtures, consolidated dates, better instructions

- src/main/java/com/easypost/model/Address.java
- src/test/java/com/easypost/AddressTest.java
- src/test/java/com/easypost/Fixture.java
Add wrapperParam when creating an address and put `verification` in the top-level param instead of inside the `address` param. 
Minor change in the fixture file and adjust unit test.
E2E tested it, see screenshot below.
> remove additional code that add strict and verify_strict to url query.

- CHANGELOG.md
- src/main/java/com/easypost/model/Address.java
- src/main/java/com/easypost/model/AddressVerifications.java
- src/test/java/com/easypost/AddressTest.java
Add missing classes: `verification`, `verifications`, and `verificationDetails`
Add extra assertion for `createAndVerify` Address.
Correct the type of `Verifications` in Address class attribute, according to our [API Doc](https://www.easypost.com/docs/api#verification-object). 
E2E tested locally
> Verification

- CHANGELOG.md
- README.md
Adds missing upgrade guide link to README and CHANGELOG
> docs: add missing upgrade guide

- CHANGELOG.md
- src/main/java/com/easypost/model/Order.java
- src/main/java/com/easypost/model/Pickup.java
- src/main/java/com/easypost/model/PickupRate.java
- src/main/java/com/easypost/model/Rate.java
- src/main/java/com/easypost/model/Shipment.java
- src/main/java/com/easypost/model/TimeInTransit.java
- src/main/java/com/easypost/model/Utilities.java
- src/test/java/com/easypost/Fixture.java
- src/test/java/com/easypost/OrderTest.java
- src/test/java/com/easypost/PickupTest.java
- src/test/java/com/easypost/ShipmentTest.java
Adds a `lowestRate` functions to Orders and Pickups
Adds a `Shipment.getLowestSmartrate` function and a `shipmentLowestSmartrate` function
Added various new unit tests to ensure all lowest_rate functions work, E2E tested until Java has VCR support.
> add lowest rate, lowest_smartrate functions

- .gitignore
- CHANGELOG.md
- README.md
- pom.xml
- src/main/java-templates/com/easypost/package-info.java
- src/main/java/com/easypost/app/Readme.java
- src/main/java/com/easypost/model/PostageLabel.java
- src/main/java/com/easypost/model/RateDeserializer.java
- src/main/java/com/easypost/net/EasyPostResource.java
- src/test/java/com/easypost/Fixture.java
- src/test/java/com/easypost/PickupTest.java
- src/test/java/com/easypost/ShipmentTest.java
Clean up IDE warnings during the build
Change the setter to be public access modifier
locally built without any warning
> clean up IDE build warnings and other minor changes.

- src/test/java/com/easypost/CreditCardTest.java
- Change fund amount for unit test to match other libraries
- Specific unit test is disabled, no need to re-record cassette.
> Fix fund amount in unit test

- src/main/java/com/easypost/model/CarrierAccount.java
- src/main/java/com/easypost/model/Field.java
- src/main/java/com/easypost/model/Fields.java
We are missing a number of properties for the `CarrierAccount` class.
- Add Fields and Field classes
- Add missing properties to CarrierAccount
NOTE: Getters/setters are scattered at the moment. This will be rectified by #144 
All tests pass.
> Add missing CarrierAccount properties

- CHANGELOG.md
- src/main/java/com/easypost/net/EasyPostResource.java
- src/test/java/com/easypost/TestUtils.java
Adds OS-specific details to the user-agent header
> Adds OS specific details to the user-agent header

- src/main/java/com/easypost/model/BaseCreditCard.java
- src/main/java/com/easypost/model/CreditCard.java
- src/main/java/com/easypost/model/CreditCardPriority.java
- src/main/java/com/easypost/model/PaymentMethod.java
- src/main/java/com/easypost/model/PrimaryPaymentMethod.java
- src/main/java/com/easypost/model/SecondaryPaymentMethod.java
- src/main/java/com/easypost/model/Shipment.java
- src/main/java/com/easypost/model/TimeInTransit.java
- src/main/java/com/easypost/model/beta/CreditCard.java
- src/main/java/com/easypost/model/beta/ReferralCustomer.java
improve deprecation wording, making it more concise
N/A
> improve deprecation wording

- .gitignore
- README.md
> chore: ignore env file

- src/test/cassettes/address/create_and_verify.json
- src/test/cassettes/address/create_verify.json
- src/test/cassettes/address/create_verify_array.json
- src/test/cassettes/address/create_verify_strict.json
- src/test/cassettes/address/verify.json
- src/test/java/com/easypost/AddressTest.java
- src/test/java/com/easypost/Fixture.java
Uses stronger address tests to ensure verifications work as intended.
- Updates previous tests to use a bool
- Adds a new test to ensure that arrays still work
> chore: adds stronger verify tests for addresses

- src/main/java/com/easypost/model/AddressCollection.java
- src/main/java/com/easypost/model/EndShipper.java
- src/main/java/com/easypost/model/EndShipperCollection.java
- src/main/java/com/easypost/model/beta/EndShipper.java
- src/test/cassettes/end_shipper/all.json
- src/test/cassettes/end_shipper/create.json
- src/test/cassettes/end_shipper/retrieve.json
- src/test/cassettes/end_shipper/update.json
- src/test/java/com/easypost/EndShipperTest.java
- src/test/java/com/easypost/beta/EndShipperTest.java
- Copy EndShipper class to main namespace
- Mark EndShipper beta class as deprecated
- Update EndShipper.all to return EndShipperCollection
- New EndShipperCollection class to wrap list of End Shipper objects
- Update unit tests
- Fix bad docstrings
- Unit tests updated and passing.
> Move End Shipper to general availability

- CHANGELOG.md
- src/main/java/com/easypost/model/Shipment.java
Allow user to pass in EndShipper ID in Shipment buy function
Remove unnecessary buy functions that do not have rate parameters
E2E test, will try to use Mock testing in the future
> add endshipper id in shipment buy and remove unnecessary buy functions

- CHANGELOG.md
- src/main/java/com/easypost/model/Address.java
Remove all instances of `message` and `carrier` from address verification and associated functions
Current unit tests pass
> Remove all instances of message and carrier from address verification

- CHANGELOG.md
- src/main/java/com/easypost/model/Insurance.java
- src/test/java/com/easypost/InsuranceTest.java
change the type of Insurance amount from `Float` to `String`
Unit tests pass
> Insurance type

- src/test/cassettes/end_shipper/all.json
- src/test/cassettes/end_shipper/create.json
- src/test/cassettes/end_shipper/retrieve.json
- src/test/cassettes/end_shipper/update.json
- src/test/cassettes/shipment/buy_shipment_with_end_shipper_id.json
- src/test/java/com/easypost/EndShipperTest.java
- src/test/java/com/easypost/ShipmentTest.java
Uses test mode for the EndShipper tests. Adds a new test for buying a shipment with an end shipper ID
Adds a new test for buying a shipment with an endshipper ID
> fix: test mode endshipper tests

- pom.xml
- src/test/java/com/easypost/TestUtils.java
Expires cassettes after 6 months.
A/B tested to ensure this works
> feat: expire cassettes after 6 months

- .github/workflows/ci.yml
- .gitignore
- Makefile
Adds coveralls to CI. Jacoco only generated XML and Coveralls needs lcov so we convert that with a Rust tool on CI before sending it off.
Generated the report locally which seemed to work.
> feat: adds coveralls to CI

- CHANGELOG.md
- src/main/java/com/easypost/service/CarrierAccountService.java
- src/test/cassettes/carrier_account/create_with_custom_workflow.json
- src/test/java/com/easypost/CarrierAccountTest.java
- Carrier account creation now determines endpoint based on type
- New unit test, cassette
> Use different endpoint for custom workflow carrier account creation (FedEx, UPS)

- CHANGELOG.md
- src/main/java/com/easypost/service/CarrierAccountService.java
- src/main/java/com/easypost/service/EndShipperService.java
- src/main/java/com/easypost/service/ShipmentService.java
- src/test/java/com/easypost/CarrierAccountTest.java
- src/test/java/com/easypost/EndShipperTest.java
- src/test/java/com/easypost/ShipmentTest.java
Fix a mistake that I accidentally left for Java thread-safe PR. This PR swap the parameter to make the `id` in the first argument.
Current tests pass
> swap the parameter to make id in the first argument

- CHANGELOG.md
- src/main/java/com/easypost/exception/API/EncodingError.java
- src/main/java/com/easypost/exception/API/ExternalApiError.java
- src/main/java/com/easypost/exception/API/ForbiddenError.java
- src/main/java/com/easypost/exception/API/GatewayTimeoutError.java
- src/main/java/com/easypost/exception/API/HttpError.java
- src/main/java/com/easypost/exception/API/InternalServerError.java
- src/main/java/com/easypost/exception/API/InvalidRequestError.java
- src/main/java/com/easypost/exception/API/JsonError.java
- src/main/java/com/easypost/exception/API/MethodNotAllowedError.java
- src/main/java/com/easypost/exception/API/NotFoundError.java
- src/main/java/com/easypost/exception/API/PaymentError.java
- src/main/java/com/easypost/exception/API/RateLimitError.java
- src/main/java/com/easypost/exception/API/RedirectError.java
- src/main/java/com/easypost/exception/API/ServiceUnavailableError.java
- src/main/java/com/easypost/exception/API/TimeoutError.java
- src/main/java/com/easypost/exception/API/UnauthorizedError.java
- src/main/java/com/easypost/exception/API/UnknownApiError.java
- src/main/java/com/easypost/exception/APIException.java
- src/main/java/com/easypost/exception/EasyPostException.java
- src/main/java/com/easypost/exception/General/FilteringError.java
- src/main/java/com/easypost/exception/General/InvalidObjectError.java
- src/main/java/com/easypost/exception/General/InvalidParameterError.java
- src/main/java/com/easypost/exception/General/MissingParameterError.java
- src/main/java/com/easypost/exception/General/SignatureVerificationError.java
- src/test/java/com/easypost/AddressTest.java
- src/test/java/com/easypost/CarrierAccountTest.java
- src/test/java/com/easypost/ErrorTest.java
Add a root level `APIException` class for all HTTP exceptions
Unit tests pass
> Add APIException class for all HTTP exceptions

- README.md
> fix: maven link

- CHANGELOG.md
- src/main/java/com/easypost/service/PickupService.java
- src/test/cassettes/pickup/all.json
- src/test/java/com/easypost/PickupTest.java
add retrieve all pickups function
add a new test
> add retrieve all pickups function

- pom.xml
Bumps EasyVCR since we patched some vulnerabilities
> fix: bump easyvcr to fix vulnerabilities

- CHANGELOG.md
- src/main/java/com/easypost/model/Payload.java
- src/main/java/com/easypost/model/PayloadCollection.java
- src/main/java/com/easypost/service/EventService.java
- src/test/cassettes/event/retrieve_all_payloads.json
- src/test/cassettes/event/retrieve_payload.json
- src/test/java/com/easypost/EventTest.java
- Adds `retrieveAllPayloads` and `retrievePayload` to retrieve all payloads or just a payload
add new unit tests
> add retrieve payload(s) functions

- README.md
> docs: adds link to lib docs to README

- CHANGELOG.md
- src/main/java/com/easypost/Constants.java
- src/main/java/com/easypost/model/StatelessRate.java
- src/main/java/com/easypost/model/StatelessRateDeserializer.java
- src/main/java/com/easypost/service/BetaRateService.java
- src/main/java/com/easypost/service/EasyPostClient.java
- src/main/java/com/easypost/utils/Utilities.java
- src/test/cassettes/beta_stateless_rate/retrieve_lowest_stateless_rate.json
- src/test/cassettes/beta_stateless_rate/retrieve_stateless_rates.json
- src/test/java/com/easypost/BetaRateTest.java
- src/test/java/com/easypost/BetaStatelessRateTest.java
add retrieve stateless rates function
add retrieve the lowest rate of stateless rates function
add two unit tests
> add retrieve stateless rates function

- .github/workflows/ci.yml
- Makefile
- README.md
- pom.xml
I removed the `install` step in my last commit, adding it back on CI via build and always builds on tests
> fix: build Makefile targets

- CHANGELOG.md
- src/main/java/com/easypost/model/ErrorDeserializer.java
- src/test/java/com/easypost/ErrorTest.java
Handle edge cases when deserializing error JSON, close #239 
Add two unit tests and pass
> Handle edge cases when deserializing error JSON

- src/main/java/com/easypost/Constants.java
- src/main/java/com/easypost/exception/General/EndOfPaginationError.java
Allow users to access error message template for EndOfPaginationError for whatever they might need
- N/A
> Add EndOfPaginationError message to Constants

- CHANGELOG.md
- src/main/java/com/easypost/model/EstimatedDeliveryDate.java
- src/main/java/com/easypost/model/EstimatedDeliveryDateResponse.java
- src/main/java/com/easypost/service/ShipmentService.java
- src/test/cassettes/shipment/retrieve_estimated_delivery_date.json
- src/test/java/com/easypost/Fixtures.java
- src/test/java/com/easypost/ShipmentTest.java
add retrieveEstimatedDeliveryDate function in Shipment class
add unit test
> add retrieveEstimatedDeliveryDate function in Shipment class

- pom.xml
- src/main/java/com/easypost/http/Requestor.java
- src/main/java/com/easypost/utils/InternalUtilities.java
- src/test/java/com/easypost/AddressTest.java
- src/test/java/com/easypost/BatchTest.java
- src/test/java/com/easypost/BetaReferralCustomerTest.java
- src/test/java/com/easypost/CarrierAccountTest.java
- src/test/java/com/easypost/EasyPostTest.java
- src/test/java/com/easypost/EndShipperTest.java
- src/test/java/com/easypost/ErrorTest.java
- src/test/java/com/easypost/EventTest.java
- src/test/java/com/easypost/InsuranceTest.java
- src/test/java/com/easypost/OrderTest.java
- src/test/java/com/easypost/PaymentMethodTest.java
- src/test/java/com/easypost/PickupTest.java
- src/test/java/com/easypost/ReferralTest.java
- src/test/java/com/easypost/RefundTest.java
- src/test/java/com/easypost/ReportTest.java
- src/test/java/com/easypost/ScanFormTest.java
- src/test/java/com/easypost/ShipmentTest.java
- src/test/java/com/easypost/TestUtils.java
- src/test/java/com/easypost/ThreadTest.java
- src/test/java/com/easypost/TrackerTest.java
- src/test/java/com/easypost/WebhookTest.java
Fixed the warnings that were thrown from Error Prone and VS code.
Added missing docstrings
Removed the deprecated functions in unit tests and used the latest equivalent functions
> fix warnings from error prone

- README.md
- src/main/java/com/easypost/exception/APIException.java
- src/main/java/com/easypost/hooks/RequestHook.java
- src/main/java/com/easypost/hooks/ResponseHook.java
- src/main/java/com/easypost/http/Requestor.java
- src/main/java/com/easypost/model/CarrierMetadata.java
- src/main/java/com/easypost/model/Error.java
- src/main/java/com/easypost/service/AddressService.java
- src/main/java/com/easypost/service/BetaCarrierMetadataService.java
- src/main/java/com/easypost/service/BetaReferralCustomerService.java
- src/main/java/com/easypost/service/CarrierMetadataService.java
- src/main/java/com/easypost/service/EasyPostClient.java
- src/main/java/com/easypost/service/EventService.java
- src/main/java/com/easypost/service/InsuranceService.java
- src/main/java/com/easypost/service/PickupService.java
- src/main/java/com/easypost/service/ReferralCustomerService.java
- src/main/java/com/easypost/service/RefundService.java
- src/main/java/com/easypost/service/ReportService.java
- src/main/java/com/easypost/service/ScanformService.java
- src/main/java/com/easypost/service/ShipmentService.java
- src/main/java/com/easypost/service/TrackerService.java
- src/main/java/com/easypost/utils/Utilities.java
- src/test/java/com/easypost/BetaRateTest.java
- src/test/java/com/easypost/BetaReferralCustomerTest.java
- src/test/java/com/easypost/Fixtures.java
- src/test/java/com/easypost/HookTest.java
Fix warnings from error prone during build, some warnings are invalid so `@suppresswarnings` is used
> Fix build warnings

- src/main/java/com/easypost/model/AddressVerificationDeserializer.java
> remove unused variable and import to clean up the build

- .github/workflows/ci.yml
- Add Java 22 to CI test matrix
- Use Java 22 (latest) for CI single tasks
> [chore] Add Java 22 support

- README.md
- src/main/java/com/easypost/http/package-info.java
- src/main/java/com/easypost/utils/package-info.java
> fix: docs link

- CHANGELOG.md
- src/main/java/com/easypost/model/DeliveryDateForZipPairEstimate.java
- src/main/java/com/easypost/model/EstimateDeliveryDateForZipPairResult.java
- src/main/java/com/easypost/model/RecommendShipDateForShipmentResult.java
- src/main/java/com/easypost/model/RecommendShipDateForZipPairResult.java
- src/main/java/com/easypost/model/RecommendShipDateResponse.java
- src/main/java/com/easypost/model/ShipDateForZipPairRecommendation.java
- src/main/java/com/easypost/model/TimeInTransitDetailsForDeliveryDate.java
- src/main/java/com/easypost/model/TimeInTransitDetailsForShipDate.java
- src/main/java/com/easypost/model/TimeInTransitDetailsForShipDateRecommendation.java
- src/main/java/com/easypost/service/EasyPostClient.java
- src/main/java/com/easypost/service/ShipmentService.java
- src/main/java/com/easypost/service/SmartRateService.java
- src/test/cassettes/shipment/retrieve_recommend_date.json
- src/test/cassettes/smart_rate/retrieve_estimated_delivery_date.json
- src/test/cassettes/smart_rate/retrieve_recommend_ship_date.json
- src/test/java/com/easypost/CarrierAccountTest.java
- src/test/java/com/easypost/Fixtures.java
- src/test/java/com/easypost/ShipmentTest.java
- src/test/java/com/easypost/SmartRateTest.java
- Adds new `shipment.recommendShipDate`, `smartrate.recommendShipDate`, and `smartrate.estimateDeliveryDate` functions
Add unit tests to make sure they are working
> Add smartrate endpoints functions

- CHANGELOG.md
- src/main/java/com/easypost/model/ChildUserCollection.java
- src/test/cassettes/user/get_next_page.json
Endpoint uses "after_id", not "before_id"
> [bug] Fix pagination parameters for listing child users

- .github/workflows/ci.yml
- pom.xml
> Java 23 Compatibility

- Makefile
Unsure why, but somewhere the output api docs path changed so this corrects it to fix the master branch.
> fix: docs copy command reference
