src/main/java/com/easypost/model/EventDeserializer.java
src/test/java/com/easypost/EasyPostTest.java
src/test/java/com/easypost/EventTest.java

We are receiving intermittent WebHook callback event containing `"previous_attributes": null`.  This causes GSON to throw `com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Not a JSON Object: null`.  This PR fixes `EventDeserializer` to handle the null.  
Also added a test case for this, and fixed 2 other tests to get them all to pass.

Handle null previous_attributes

---

src/main/java/com/easypost/model/Order.java
src/main/java/com/easypost/model/Pickup.java

Removed the unpaginated endpoints for orders and pickups for the `all` method.

Removing unpaginated all endpoints from orders and pickups

---

src/main/java/com/easypost/model/Shipment.java

Starting soon in the future, getRates() will always be read-only (as you would expect from a GET), and re-rating will be triggered through the newRates() function. This adjusts the newRates function. No change has occurred to getRates() yet.

use the new rerate api for rerating

---

CHANGELOG.md
src/main/java/com/easypost/net/EasyPostResource.java

We haven't used the `contact@easypost.com` email for some time for support inquiries, correct it to `support@easypost.com`.

fix: corrects support email in error messages

---

src/test/java/com/easypost/EasyPostTest.java

Fixed the assertEquals parameters issue, swap the parameters from **(actual, expected)** to **(expected, actual)**.
This improves the accuracy of overall testing.
closes #66

fixed assertEquals parameters issue

---

.gitignore
src/main/java/com/easypost/model/Tracker.java
src/main/java/com/easypost/net/EasyPostResource.java
src/test/java/com/easypost/EasyPostTest.java

Java library will now send data as JSON in the request body for POST and PUT requests, rather than sending them as urlencoded data.
Still uses urlencoded data for GET and DELETE functions.
This allows for future support for things such as Tax Identifiers.

Migrate from urlencoded to JSON bodies for POST/PUT requests

---

src/test/java/com/easypost/EasyPostTest.java

Fixes an incorrect expected value that will cause the test to fail. Must have gotten lost in a rebase.

Fix incorrect test value

---

README.md
pom.xml

Bumps the plugins we use during development, has no impact on the library itself. Also removes the now incorrect `Java 1.5` requirement from the README

chore: bump plugins, remove bad Java README version

---

src/main/java/com/easypost/model/Tracker.java
src/test/java/com/easypost/EasyPostTest.java

Improve the **createList** method in the Tracker class
Currently, our **createList** method in the Tracker class is doing extra work which refactors the user input. The user is also creating an extra list and map. Overall, this extra work would downgrade the runtime performance which takes O(n) time complexity for **createList** method, and when the user mistypes "trackers" as the key for input map, a NullPointerException could be thrown.
Instead of asking the user to input a map that **must** have "**trackers**" as the key and a list of maps as value, we now just need the user to enter a map of maps where the key is the number of trackers and value is a map of **tracking_code** and **carrier**.
Modify the unit test to accommodate the code change.

Improve create list tracker

---

CHANGELOG.md

RE: https://github.com/EasyPost/easypost-java/pull/93
- Update CHANGELOG.md: Allow users to override default API timeouts

Update changelog for new feature

---

src/main/java/com/easypost/net/EasyPostResource.java
src/test/java/com/easypost/EasyPostTest.java

We had a bad testing setup, where the test for changing the API timeouts was running before other tests. Without resetting the timeouts, they were too aggressive and were causing other tests to fail.
This PR includes:
- Public (but immutable) default timeout values, so can be accessed if needed (i.e. to reset values)
- Corrected timeout test that resets what it changed after executing, so other tests can run correctly.

Fix timeout values in test

---

src/test/java/com/easypost/AddressTest.java
src/test/java/com/easypost/BatchTest.java
src/test/java/com/easypost/CarrierAccountTest.java
src/test/java/com/easypost/EventTest.java
src/test/java/com/easypost/InsuranceTest.java
src/test/java/com/easypost/RefundTest.java
src/test/java/com/easypost/ReportTest.java
src/test/java/com/easypost/ScanFormTest.java
src/test/java/com/easypost/ShipmentTest.java
src/test/java/com/easypost/TrackerTest.java
src/test/java/com/easypost/WebhookTest.java

This PR converts a loop of assertion to **stream()** for **testAll()** in all unit tests.

use stream() instead of loop in unit tests.

---

src/test/java/com/easypost/ShipmentTest.java

Adds a test when only IDs are passed to object creation. This was brought up as a way to check behavior across all libs due to: https://github.com/EasyPost/easypost-node/issues/222

chore: add shipment ID test

---

CHANGELOG.md
src/main/java/com/easypost/model/Report.java
src/test/java/com/easypost/ReportTest.java

This PR adds support for specifying `columns` and `additional_columns` in the params for the report create method.
Adds two unit tests for this feature. E2E test and download the CSV report to check if the result is correct.
Additional columns and columns in the param, total three columns (from_name, from_company, usps_zone)
Only columns in the param, only one column (usps_zone)

Support `columns` and `additional_columns` for reports

---

src/main/java/com/easypost/model/Report.java

This PR moves the `columns` and `additional_columns` from URL query to request body because a long query URL can be rejected or silently truncated. 
E2E test:

move columns and additional_columns from url query to request body.

---

src/main/java/com/easypost/model/Report.java

This PR removes the `wrapperParam` to make the code cleaner, add an exception when the user input does not contain `type` for report creation.

minor improvement on report creation.

---

CHANGELOG.md
src/main/java/com/easypost/model/CustomsInfo.java

Customs Info class is currently missing the `declaration` attribute.
This PR adds the `declaration` attribute in the Customs Info class.

add declaration attribute in customs info class.

---

.github/workflows/ci.yml
src/main/java/com/easypost/model/Address.java

This PR removes code that adds `strict` and `verify_strict` to the URL query when the API method is `POST`. The `wrappedParams` is also removed since it does not do anything. 
Since Java CL is the only library that does not have VCR yet, E2E is locally tested.

remove additional code that add strict and verify_strict to url query.

---

src/main/java/com/easypost/model/ShipmentMessage.java

While fixing a [similar issue](https://github.com/EasyPost/easypost-csharp/pull/250) in our C# library, we noticed that the `carrierAccountId` element in messages for Pickups was not being deserialized.
- Adds `carrierAccountId` as attribute in `ShipmentMessage` class
E2E tested

Add `carrierAccountId` to ShipmentMessage

---

README.md

Removes the `Gradle` install instructions in the README until we support it.

docs: remove Gradle install info until supported

---

CHANGELOG.md
src/main/java/com/easypost/model/Shipment.java
src/test/java/com/easypost/ShipmentTest.java

To avoid confusion between proper getter/setter functions and other functions that merely start with the word `get`, all non-getter `getX` functions have been renamed to simply `X` (i.e. `getLowestSmartrate()` -> `lowestSmartrate()`).
This will avoid unnecessary exception throwing and catching during object merges, which utilizes getter/setter pairs and gets confused when there is no `setX` for a given `getX` function.
All tests pass as expected.

Rename non-getter `getX` methods

---

src/main/java/com/easypost/model/Shipment.java
src/main/java/com/easypost/model/SmartrateAccuracy.java
src/main/java/com/easypost/model/TimeInTransit.java
src/test/java/com/easypost/ShipmentTest.java

- New SmartrateAccuracy enum (similar to [C# library](https://github.com/EasyPost/easypost-csharp/blob/master/EasyPost/Smartrate.cs))
- New functions to use SmartrateAccuracy when dealing with smartrates
- Deprecate old smartrate functions using strings
- Unit tests updated to use new functions
- No new unit tests
- No new cassettes needed
- No new recordings needed

Migrate to using enums for Smartrate delivery accuracy choices

---

.github/workflows/ci.yml
Makefile
pom.xml

- Add dependency-check as dependency
- Add Makefile for common commands (lint, security check, build, release, publish, etc)
- Add CI step (see notes)
- All Makefile commands work as expected
- Dependency check runs from command line as expected
- All unit tests pass as expected, no changes or re-recording needed
- The dependency check generates an HTML report after running, which is then uploaded as an artifact (example below). The CI step itself should fail on severe CVSs (plugin is configured to fail a build if there are any CVSs with a score 7+)
- There is also a [free GitHub integration](https://github.com/marketplace/muse-dev/plan/MLP_kgDNGN8) from Sonatype (who run the Maven repository) to scan for CVSs, that we might want to consider. This should be in addition to the CI tool, not …

Security analysis and Makefile

---

CHANGELOG.md
src/main/java/com/easypost/model/Shipment.java
src/test/cassettes/shipment/generate_form.json
src/test/java/com/easypost/Fixture.java
src/test/java/com/easypost/ShipmentTest.java

Add `generate_form` function in the Shipment class to allow the user to create a form from a shipment object.
Added a new unit test and passed it

Add generateForm function to Shipment class

---

src/main/java/com/easypost/net/EasyPostResource.java
src/test/cassettes/shipment/regenerate_rates.json
src/test/cassettes/shipment/regenerate_rates_with_carbon_offset.json

We noticed that, despite it being deprecated, the old `getSmartrates` function is still being called when updating a shipment, as our merge function believes it is a getter. This results in erroneous API calls.
The old function is slated for removal "eventually", but until then, we need to skip the function.
Rather than hard-coding a skip for this specific function, we have added an if clause to the merge functionality that checks if a function is marked as deprecated. If it is, the function is skipped.
- All unit tests pass as expected
- Re-recorded two cassettes that had the bad API call in them. Confirmed that bad API call is no longer being made after fix.

Skip deprecated functions when merging objects

---

.github/workflows/ci.yml
Makefile
README.md

Unifies the Makefile targets like we've done in other libs. Also adds a `release` target.
- Tested the new targets locally to ensure they worked. Used the `release` target successfully in prod to release `v5.8.1` and all built assets.

chore: unify Makefile and add release target

---

.github/workflows/ci.yml

- CI build will pull Maven dependencies (including CVE database) from cache
CVE database and Maven dependencies pulled successfully:
First run (when cache wasn't present), security scan step took ~3 minutes due to having to download the database.
Re-run (with cache now present), security scan step took ~20 seconds, did not need to re-download the database.
Even after a new commit (in case re-run uses cache by default), same result, security scan step did not need to re-download the database, suggesting that cache is working as expected.
Overall, with cache being used for Maven dependencies and CVE database for all `build` and `security` processes, the entire CI suite completed in record time, with all processes taking less than 1 minute each.
Please select the option(s) that are relevant …

Cache Maven dependencies, CVE database on CI

---

CHANGELOG.md
src/main/java/com/easypost/model/Billing.java
src/main/java/com/easypost/model/ReferralCustomer.java
src/main/java/com/easypost/model/Tracker.java
src/test/java/com/easypost/BillingTest.java
src/test/java/com/easypost/CarrierAccountTest.java
src/test/java/com/easypost/ReferralTest.java
src/test/java/com/easypost/TrackerTest.java
src/test/java/com/easypost/UserTest.java
src/test/java/com/easypost/WebhookTest.java

- Converts return type from boolean to void in empty response body functions
- `fundWallet()` and `deletePaymentMethod()` in Billing class
- `createList()` in Tracker class
- `updateEmail()` in ReferralCustomer class
Current unit tests pass

convert return type for fundWallet and deletePaymentMethod

---

src/main/java/com/easypost/net/EasyPostResource.java
src/test/java/com/easypost/AddressTest.java
src/test/java/com/easypost/CarrierAccountTest.java
src/test/java/com/easypost/CustomsInfoTest.java
src/test/java/com/easypost/CustomsItemTest.java
src/test/java/com/easypost/ParcelTest.java
src/test/java/com/easypost/PickupTest.java
src/test/java/com/easypost/RateTest.java
src/test/java/com/easypost/RefundTest.java
src/test/java/com/easypost/ScanFormTest.java
src/test/java/com/easypost/ShipmentTest.java
src/test/java/com/easypost/WebhookTest.java

Override `equals()` that convert objects to JSON strings for comparison, which compares two objects' properties
Override `hashcode()` is needed: https://www.baeldung.com/java-equals-hashcode-contracts#hashcode
Update unit tests with override `equals()`
Current unit tests pass

override equals() and hashcode()

---

pom.xml

Remove `assertj` dependency since it's no longer being used, this will also make a dependency less on the `Test Dependencies` in our [Java Maven page](https://mvnrepository.com/artifact/com.easypost/easypost-api-client/5.10.0). We have overridden the `equal()` for object comparison in this [PR](https://github.com/EasyPost/easypost-java/pull/191)
Current unit tests pass.

remove assertj dependency

---

README.md
src/main/java-templates/com/easypost/EasyPost.java

Adds install info for Gradle back to the README. Also clarifies info about building with Gradle (specifically the VERSION variable will not be populated).
NA

chore: re-add Gradle install info and specify VERSION info when using Gradle

---

.github/workflows/ci.yml

`grcov` previously didn't aggregate the path data correctly and was showing 0% coverage, this is fixed by passing a couple extra flags.
I commented out the master branch check to see if it published to coveralls correctly which it did so this change definitely fixes the problem.

fix: coverage generation for coveralls

---

UPGRADE_GUIDE.md
src/main/java/com/easypost/exception/API/ExternalApiError.java
src/main/java/com/easypost/service/ReferralCustomerService.java
src/test/java/com/easypost/ReferralTest.java

Add content for the V6 major bump in the upgrade guide
Move the `ExternalApiError` from the general to API folder
N/A

Add content to upgrade guide for v6 major bump

---

.github/workflows/ci.yml
src/main/java/com/easypost/service/ReferralCustomerService.java
src/test/cassettes/referral/referral_add_credit_card.json
src/test/cassettes/shipment/create_with_ids.json
src/test/java/com/easypost/ReferralTest.java
src/test/java/com/easypost/ShipmentTest.java

- Fix unit tests disabled due to EasyVCR issues:
Summary:
- Referral credit card - The API calls to Stripe use a temporary client that was not configured to use EasyVCR. API calls to Stripe were not being recorded/replayed, and instead live data was being used. The live API calls returned data that did not match expected data in later EasyPost API calls, causing it to fail.
- The client used for Stripe calls has been configured to use EasyVCR on testing. Additional tweaks to the URL encoding for Stripe API calls fixed HTTP issues.
- Create shipment by IDs - Creating a shipment involves creating two addresses. Both API calls included the same exact request parameters. EasyVCR is configured to record a request if it does not already exist in the cassette (only considering request …

Fix EasyVCR-related issues for unit tests

---

CHANGELOG.md
README.md
pom.xml
src/main/java/com/easypost/model/BetaPaymentRefund.java
src/main/java/com/easypost/service/BetaReferralCustomerService.java
src/main/java/com/easypost/service/EasyPostClient.java
src/test/cassettes/beta_referral_customer/add_payment_method.json
src/test/cassettes/beta_referral_customer/refund_by_amount.json
src/test/cassettes/beta_referral_customer/refund_by_payment_log_id.json
src/test/java/com/easypost/BetaReferralCustomerTest.java
src/test/java/com/easypost/TestUtils.java

Add new beta billing functionality for ReferralCustomer users
- `addPaymentMethod` can add a pre-existing Stripe bank account or credit card to your EasyPost account
- `refundByAmount` refunds your wallet by a dollar amount
- `refundByPaymentLog` refunds your wallet by a PaymentLog ID
Add new unit tests

add new billing functionality that allow user to add/refund payment

---

pom.xml
src/main/java/com/easypost/utils/ApachePatch.java
src/main/java/com/easypost/utils/Cryptography.java
style_suppressions.xml

- Extract required Apache functions (hex conversion) into ApachePatch
- Drop vulnerable Apache dependencies
There were two Apache dependencies being imported into this library, `httpcomponents` (explicitly) and `common-codec` (implicitly) both of which were vulnerable.
Turns out `httpcomponents` was not being used anywhere, and could simply be dropped.
`common-codec` was being used solely for its Hex class, used for hexidecimal conversion for webhook validation. The necessary functions from that class have been extracted into a `ApachePatch` internal utility file, allowing us to drop the vulnerable dependency forever. This, of course, will not stop `common-codec` from being imported into our library via the ErrorProne plugin, but will at least ensure we are not utilizing the vulnerable …

Drop vulnerable Apache dependencies, implement dependent functions

---

src/main/java/com/easypost/utils/ApachePatch.java

Removes a bunch of overloaded methods ported from the Apache hex library, only keep what we need.
This will reduce the number of uncovered lines significantly.
- All unit tests pass as expected

Remove extraneous Apache port functions to bump coverage percentage

---

.github/workflows/ci.yml

It's everyone's favorite time of the year: March! Which means a new Java version: https://www.oracle.com/news/announcement/oracle-releases-java-20-2023-03-21/
- Bump CI to test against 20, still using 8 as a min target

Add Java 20 support

---

src/main/java/com/easypost/model/Shipment.java
src/main/java/com/easypost/model/ShipmentCollection.java
src/main/java/com/easypost/model/Tracker.java
src/main/java/com/easypost/model/TrackerCollection.java
src/main/java/com/easypost/service/ShipmentService.java
src/main/java/com/easypost/service/TrackerService.java
src/main/java/com/easypost/utils/InternalUtilities.java
src/test/cassettes/shipment/all_parameter_hand_off.json
src/test/cassettes/shipment/get_next_page_parameter_hand_off.json
src/test/cassettes/tracker/all_parameter_hand_off.json
src/test/cassettes/tracker/get_next_page_parameter_hand_off.json
src/test/java/com/easypost/ShipmentTest.java
src/test/java/com/easypost/TrackerTest.java

Java port of https://github.com/EasyPost/easypost-csharp/pull/424
- Adds unit tests to ensure that parameters are being captured from parameter dictionary and stored in the XCollection objects
- Adds unit tests to ensure that parameters are being extracted from XCollection objects and reused in getNextPage parameter construction
- Apologies for the hacky extended classes needed to test a protected function from a different namespace

Account for special parameters for `all()` and `getNextPage()` for shipments and trackers

---

.github/workflows/ci.yml

Our coverage step on CI (publishing coverage report when pushed to master) has been broken for a while due to an issue with one of the dependencies used in the flow.
I have personally confirmed that the latest version of the `grcov` tool used to convert reports (0.8.15) produces empty output files. The previous working version (0.8.13) still works.
This PR pins the version of `grcov` used to avoid this issue.
- Individually confirmed on local machine

[chore] Fix coverage CI

---

CHANGELOG.md
src/main/java/com/easypost/model/Payload.java

We made a silly mistake on the type for `requestBody` in the `Payload` class. After doing some internal research, the type should be String instead of Map. This PR will close #246 

fix type for requestBody in Payload class

---

CHANGELOG.md
pom.xml
src/main/java-templates/com/easypost/EasyPost.java
src/main/java/com/easypost/http/Requestor.java
src/main/java/com/easypost/service/ReferralCustomerService.java
src/test/java/com/easypost/TestUtils.java

Rather than storing a global VCR (requiring EasyVCR to be a production dependency), we now store a global Function that accepts a string and returns an `HttpsUrlConnection`. This function is set by the test suite to use the configured VCR, but this means that `EasyVCR` does not leave the test suite.
Should close #265 
- All unit tests pass, cassettes replayed as normal after rebuild (suggests that function is working as expected, no impact on flow).
- Can confirm that EasyVCR is no longer downloaded during build/install process (accidentally kept an import during testing and compiler correctly complains about a missing import)

[chore] Remove VCR as production dependency

---

CHANGELOG.md
pom.xml

Bumps all dependencies to fix some security issues.
This change introduces a bunch of new warnings during the build process, most of which about bad javadocs that need to be corrected. This can be done separately.
Unfortunately, there is still a vulnerability of a 3rd party dependency that we don't have control over. Similarly, Google hasn't released a patch in over a year so we may be SOL: 
```
One or more dependencies were identified with known vulnerabilities in com.easypost:easypost-api-client:
guava-31.1-jre.jar (pkg:maven/com.google.guava/guava@31.1-jre, cpe:2.3:a:google:guava:31.1:*:*:*:*:*:*:*) : CVE-2020-8908
```

chore: update all dependencies

---

CHANGELOG.md
src/main/java/com/easypost/Constants.java
src/main/java/com/easypost/exception/API/BadRequestError.java
src/main/java/com/easypost/http/Requestor.java
src/test/java/com/easypost/ErrorTest.java

Maps 400 status codes to the new `BadRequestError` class

feat: maps 400 status codes to BadRequestError class

---

CHANGELOG.md
src/main/java/com/easypost/Constants.java

- FedEx SmartPost carrier account registration should hit `/register` endpoint for creation

[fix] FedEx SmartPost hits register endpoint

---

src/main/java/com/easypost/service/ShipmentService.java
src/main/java/com/easypost/utils/Utilities.java
src/test/java/com/easypost/Fixtures.java

Clean up Java build warnings by:
* Adding `@InlineMe` to the deprecated function so that when users call the method tagged with `@InlineMe` will be migrated to the new method. This implementation is optional but it's worth adding it. 
* Removing the `printStackTrace()` and throw an exception instead
More resource: https://errorprone.info/docs/inlineme
E2E ran **make clean publish-dry**

clean up Java build warnings

---

dependency-check-suppressions.xml
pom.xml

The DependencyCheck plugin we use to scan for vulnerabilities in our library is, itself, vulnerable. This is a red herring that unfortunately causes our CI to fail.
This PR will ignore this known vulnerability for the time being.
This does NOT pass vulnerable code down to our end-users, as this is purely an issue with one of the plugins we use to test the library.
- `make scan` calls dependency check as expected
- Dependency scan passes as expected (no current vulnerabilities other than the aforementioned vulnerability inside the now-removed Maven plugin)

[chore] Ignore vulnerability in DependencyCheck and bumped the version

---

src/main/java/com/easypost/Constants.java
src/main/java/com/easypost/model/AddressVerification.java
src/main/java/com/easypost/model/AddressVerificationDeserializer.java
src/main/java/com/easypost/model/Error.java
src/test/java/com/easypost/AddressTest.java

Our current setup reuses the `Error` class to represent address verification errors. However, the `Error` class has a custom deserializer that is being called during typical JSON deserialization in our library. Hard-coded logic inside that deserializer was effectively causing deserialization of the hints for address verification to fail.
This PR introduces another custom deserializer, specifically for the `AddressVerification` class that handles deserializing address verification JSON without the `Error` deserializer getting in the way.
Closes #288 
- Improved existing unit test to verify that deserialization worked properly (that address verification details were not lost during deserialization)

[fix] Address verification details lost during deserialization

---

.github/workflows/ci.yml
pom.xml

Add java 21 in the CI build 
Bump lombok to support JDK 21 

Add Java 21 in the CI build

---

CHANGELOG.md
src/main/java/com/easypost/model/EasyPostTimeInTransitData.java
src/main/java/com/easypost/model/EstimatedDeliveryDate.java
src/test/java/com/easypost/ShipmentTest.java

`EasyPostTimeInTransitData` was not explicitly marked as public, making it inaccessible to end-users.
Closes #304 
- Unit test updated to confirm class/property of `EstimatedDeliveryDate` is accessible

[Fix] Public accessibility of `EasyPostTimeInTransitData` class

---

CHANGELOG.md
src/main/java/com/easypost/model/PaymentMethodObject.java
src/test/java/com/easypost/BillingTest.java

- Use payment method object type as fallback when determining type for fund, delete functions
- Update, add unit test to confirm legacy (by ID prefix) and new (by object type) both work to determine payment method type

[bug] Cannot determine payment method when funding/deleting

---

CHANGELOG.md
src/main/java/com/easypost/model/EasyPostResource.java
src/test/cassettes/easypost_resource/pretty_print.json
src/test/cassettes/easypost_resource/to_string.json
src/test/java/com/easypost/EasyPostResourceTest.java

Previous method of reflection to retrieve the `id` of an `EasyPostResource` often failed, resulting in fallback to empty string. As a result, the string representation of any `EasyPostResource` was often an empty string.
New method improves `toString` calculation, including accounting for present/non-present `id` field (ephemeral objects).

[fix] ID field usage in string representation of EasyPost objects

---

CHANGELOG.md
src/main/java/com/easypost/model/CarrierAccount.java
src/main/java/com/easypost/model/Field.java
src/main/java/com/easypost/model/Fields.java
src/test/java/com/easypost/BillingTest.java
src/test/java/com/easypost/CarrierAccountTest.java

Port of [fix in .NET library](https://github.com/EasyPost/easypost-csharp/pull/558) to Java.
Fun fact: The `Fields` object in this library previously did not have any properties declared. This means there was never any deserialization issues, but also means that each `Field` was never reachable by end-users.
- Add unit test to confirm deserialization works as expected
- The carrier accounts used in our existing unit tests do not have fields returned by the API, so the serialization issue was not previously caught.
- Beyond that, the properties of `Fields` were not declared, so they were never deserialized.

[fix] Invalid `Fields` structure

---

CHANGELOG.md
Makefile
src/main/java/com/easypost/Constants.java
src/main/java/com/easypost/service/CarrierAccountService.java
src/test/cassettes/carrier_account/create_with_ups.json
src/test/cassettes/carrier_account/update_ups.json
src/test/java/com/easypost/CarrierAccountTest.java

Update CarrierService `create` and `update` method to account UPS OAuth endpoints
Add unit tests to make sure we are hitting the correct endpoints.

Update CarrierService create and update methods

---

CHANGELOG.md
src/main/java/com/easypost/Constants.java
src/main/java/com/easypost/model/Claim.java
src/main/java/com/easypost/model/ClaimCollection.java
src/main/java/com/easypost/model/ClaimHistoryEntry.java
src/main/java/com/easypost/model/DateDeserializer.java
src/main/java/com/easypost/service/ClaimService.java
src/main/java/com/easypost/service/EasyPostClient.java
src/test/cassettes/claim/all.json
src/test/cassettes/claim/cancel.json
src/test/cassettes/claim/create.json
src/test/cassettes/claim/get_next_page.json
src/test/cassettes/claim/retrieve.json
src/test/java/com/easypost/ClaimTest.java
src/test/java/com/easypost/Fixtures.java
src/test/java/com/easypost/fixtures/FixtureStructure.java
src/test/java/com/easypost/fixtures/components/Claims.java

- Add new `Claim` service for filing claims on EasyPost shipments and insurances
Add unit tests

Add Claims service

---

CHANGELOG.md
src/main/java/com/easypost/http/Requestor.java
src/test/cassettes/hook/http_error.json
src/test/java/com/easypost/CarrierAccountTest.java
src/test/java/com/easypost/HookTest.java

Fix an order-of-operations bug where API errors were being parsed (and potential exceptions thrown) before firing response hooks, meaning response hooks were not being triggered if an API call was unsuccessful.
Closes #321 
- New unit test to confirm response hook gets fired even when an API error occurs.

[fix] Fire response hook before parsing API error to avoid early exit

---

.github/workflows/publish.yml
pom.xml

Use GitHub Actions to build/publish JARs to Maven Central Repository (and attach them to GitHub release) upon creating a GitHub release.
Ref: https://github.com/actions/setup-java/blob/v3.11.0/docs/advanced-usage.md#publishing-using-apache-maven
Awaiting required secrets to be added to GitHub Secrets on this repo.

[chore] Set up Actions-based release process

---

.github/workflows/ci.yml
.github/workflows/publish.yml
Makefile

The release failed because we weren't installing our styleguide so the process could check it. This fixes the makefile targets to allow us to use a styleguide specific one for releasing and clarifies and updates the dependencies for this on normal installs.

fix: style make targets to pass during release

---

.github/workflows/ci.yml
.github/workflows/publish.yml
CHANGELOG.md
Makefile
pom.xml
src/main/java/com/easypost/model/Webhook.java
src/main/java/com/easypost/model/WebhookCustomHeader.java
src/main/java/com/easypost/service/WebhookService.java
src/test/cassettes/webhook/all.json
src/test/cassettes/webhook/create.json
src/test/cassettes/webhook/delete.json
src/test/cassettes/webhook/retrieve.json
src/test/cassettes/webhook/update.json
src/test/java/com/easypost/Fixtures.java
src/test/java/com/easypost/TestUtils.java
src/test/java/com/easypost/WebhookTest.java
src/test/java/com/easypost/fixtures/FixtureStructure.java
src/test/java/com/easypost/fixtures/components/Webhooks.java

- Adds `WebhookCustomHeader` model, allowing `custom_headers` to be passed when creating/updating a webhook
- Corrects payload wrapping for updating a webhook
- Bumps dependencies
- Tests new webhook params

test: extra webhook params

---

.github/workflows/ci.yml
.github/workflows/publish.yml
CHANGELOG.md
src/main/java/com/easypost/model/TimeInTransit.java
src/main/java/com/easypost/model/TrackerCollection.java
src/main/java/com/easypost/service/PaymentMethodService.java
src/main/java/com/easypost/service/ShipmentService.java
src/main/java/com/easypost/service/TrackerService.java
src/main/java/com/easypost/service/UserService.java
src/main/java/com/easypost/utils/Utilities.java
src/test/java/com/easypost/ShipmentTest.java

- Adds `tracking_codes` to tracker list function
- Removes deprecated functions
- `TimeInTransit.getSmartRateAccuracy` (use `TimeInTransit.getSmartrateAccuracy` instead)
- `paymentMethod.all` (use `billing.retrievePaymentMethods` instead)
- `shipment.getSmartrates` (use `shipment.smartrates` instead)
- String overload for `shipment.lowestSmartRate`, 3rd param requires a valid `SmartrateAccuracy`
- `user.apiKeys` (use `apiKey.retrieveApiKeysForUser` instead)
- `utilities.getLowestSmartRate` (use `utilities.findLowestSmartrate` instead)
NA

chore: remove deprecated functions
